apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: java-demo-vn
  namespace: testing
spec:
  podSelector:
    matchLabels:
      app: java-demo
  listeners:
    - portMapping:
        port: 8080
        protocol: http
  serviceDiscovery:
    dns:
      hostname: java-demo.testing.svc.cluster.local
