apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: java-demo-vs
  namespace: testing
spec:
  awsName: java-demo-svc.testing.svc.cluster.local
  provider:
    virtualRouter:
      virtualRouterRef:
        name: java-demo-vr
---
apiVersion: v1
kind: Service
metadata:
  name: java-demo-svc
  namespace: testing
spec:
  ports:
    - port: 8080
      name: http
